#include "command_word.h"

const char *cmd_phoneme[] = {
    "ping tang mo shi",
    "xiu xian mo shi",
    "shen shui mo shi",
    "zhu mian mo shi",
    "fang song mo shi",
    "jian ya mo shi",
    "tou bu shang sheng",
    "tou bu xia jiang",
    "jiao bu shang sheng",
    "jiao bu xia jiang",
    "ting zhi",
    "tong bu shang sheng",
    "tong bu xia jiang",
    "tou bu fang song",
    "guan bi tou bu fang song",
    "jiao bu fang song",
    "guan bi jiao bu fang song",
    "da kai fang song",
    "guan bi fang song",
    "mo shi yi",
    "mo shi er",
    "mo shi san",
    "fang song shi fen zhong",
    "fang song er shi fen zhong",
    "fang song san shi fen zhong",
    "da kai deng",
    "guan bi deng",
    "hu yao mo shi",
    "zuo bian hu yao mo shi",
    "you bian hu yao mo shi",
    "hu yao tiao ruan",
    "zuo bian hu yao tiao ruan",
    "you bian hu yao tiao ruan",
    "hu yao tiao ying",
    "zuo bian hu yao tiao ying",
    "you bian hu yao tiao ying",
    "guan bi hu yao",
    "guan bi zuo bian hu yao",
    "guan bi you bian hu yao",
    "da kai heng wen",
    "guan bi heng wen",
    "tou bu ling dang",
    "tou bu yi dang",
    "tou bu er dang",
    "tou bu san dang",
    "tou bu si dang",
    "tou bu wu dang",
    "tou bu liu dang",
    "tou bu qi dang",
    "tou bu ba dang",
    "tou bu jiu dang",
    "tou bu shi dang",
    "jiao bu ling dang",
    "jiao bu yi dang",
    "jiao bu er dang",
    "jiao bu san dang",
    "jiao bu si dang",
    "jiao bu wu dang",
    "jiao bu liu dang",
    "jiao bu qi dang",
    "jiao bu ba dang",
    "jiao bu jiu dang",
    "jiao bu shi dang"
};

const size_t command_word_count = sizeof(cmd_phoneme) / sizeof(cmd_phoneme[0]);
